### ISSUE TITLE
Prepare 0.1-rc1 release

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#105]
- [x] https://github.com/istio-ecosystem/sail-operator/issues/107
- [x] https://github.com/istio-ecosystem/sail-operator/issues/108
- [x] https://github.com/istio-ecosystem/sail-operator/issues/199
- [x] https://github.com/istio-ecosystem/sail-operator/issues/222
- [x] https://github.com/istio-ecosystem/sail-operator/issues/288
