### ISSUE TITLE
Create user documentation under /docs

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#106]
We'll need to update our user documentation, as the README.md doesn't cover all of the features of the sail-operator anymore. It should be in Markdown and cover all major features and API resources.

- [x] https://github.com/istio-ecosystem/sail-operator/issues/147
- [x] https://github.com/istio-ecosystem/sail-operator/issues/181
- [x] https://github.com/istio-ecosystem/sail-operator/issues/182
- [x] https://github.com/istio-ecosystem/sail-operator/issues/207
- [x] https://github.com/istio-ecosystem/sail-operator/issues/217
- [x] https://github.com/istio-ecosystem/sail-operator/issues/324
- [x] https://github.com/istio-ecosystem/sail-operator/issues/406
