### ISSUE TITLE
[EPIC] Ambient mode support in Sail Operator

### ISSUE THREAD

**Issue by sridhargaddam** [istio-ecosystem/sail-operator#500]
### Epic Description

Add necessary support in the Sail Operator to deploy Istio in Ambient mode.
- [x] [Implement API and CRD for ztunnel component](https://github.com/istio-ecosystem/sail-operator/pull/481)
- [x] [Update ztunnel versions in update_version-list.sh](https://github.com/istio-ecosystem/sail-operator/pull/509)
- [x] [Implement controller for managing lifecycle of ztunnel](https://github.com/istio-ecosystem/sail-operator/pull/512)
- [x] [Fix `make undeploy` in an Ambient deployment](https://github.com/istio-ecosystem/sail-operator/pull/533) 
- [x] [Allow overriding Ambient params in IstioCNI](https://github.com/istio-ecosystem/sail-operator/pull/563) 
- [x] [Implement an e2e test for Ambient config in IstioCNI](https://github.com/istio-ecosystem/sail-operator/pull/591) 
- [x] [Fix ztunnel controller to apply values.ztunnel config](https://github.com/istio-ecosystem/sail-operator/pull/568)
- [x] [Use logAsJson instead of logAsJSON in ZTunnel APIs](https://github.com/istio-ecosystem/sail-operator/pull/584) 
- [x] [Add necessary e2e tests for Sail Operator ztunnel controller.](https://github.com/istio-ecosystem/sail-operator/pull/541)
- [x] [Enhance make commands for ambient support and platform auto-discovery](https://github.com/istio-ecosystem/sail-operator/issues/545) 
- [x] [Create Ambient developer documentation.](https://github.com/istio-ecosystem/sail-operator/pull/579)
- [x] [Update Ambient docs with waypoint user-guide.](https://github.com/istio-ecosystem/sail-operator/pull/694)
