### ISSUE TITLE
Release Automation

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#85]
- [x] https://github.com/istio-ecosystem/sail-operator/issues/84
- [x] https://github.com/istio-ecosystem/sail-operator/issues/110
- [x] https://github.com/istio-ecosystem/sail-operator/issues/210
- [x] https://github.com/istio-ecosystem/sail-operator/issues/216
- [x] https://github.com/istio-ecosystem/sail-operator/issues/289
- [x] https://github.com/istio-ecosystem/sail-operator/issues/290
