### ISSUE TITLE
Repository Setup

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#87]
- [x] https://github.com/istio-ecosystem/sail-operator/issues/78
- [x] https://github.com/istio-ecosystem/sail-operator/issues/98
- [x] https://github.com/istio-ecosystem/sail-operator/issues/104

**Comment by fjglira** [comment]
All the task related to this are closed
